Network:
  batch_size: 1
  lr: 1e-4
  weight_decay: 0
  amsgrad: False
  image_downsample: False  # if we want to downsample the images; otherwise we will crop a patch from images.
  resize_shape: [80, 80, 80]  # d, h, w (training data are also stored in d, h, w). after cropping.

augmentation:
  patch_size: [128, 128, 128]  # if we don't use image down sampling, patches of this size will be cropped from original image
  general_spatial_probability: 0.5  # probability of having spatial data augmentation at all
  general_intensity_probability: 0.5  # probability of having intensity data augmentation at all
  lateral_flip_prob: 0.4  # probability of having lateral flipping augmentation
  interior_flip_prob: 0.4  # probability of having interior flipping augmentation
  zoom_range: [1, 1.15]  # 0.1 means from 0.9 to 1.1
  gamma_range: [0.8, 1.2]  # based on own implementation
  gamma_prob: 0.4  # probability of having gamma augmentation
  mu_AWGN: 0.0  # mean of AWGN
  sigma_AWGN: 0.03  # std of AWGN; don't go more than 0.03
  AWGN_prob: 0.2  # probability of having AWGN augmentation

network_output_path: network_data/
output_data_path: output_data/
tb_logs_path: tensor_board_logs/
stat_log_path: stat_logs
checkpoint_name: checkpoint.tar
trained_model_name: trained_model.pth
class_weights_3: [0.60484207, 0.05533713, 0.3366944]  # for 3 classes
class_weights: [0.00312639, 0.60484207, 0.05533713, 0.3366944]
  # for BraTS20

# Paths to the dataset
T_DATASET_PATH: '/home/fahim/F2NetViT/Data/train_list.txt'
V_DATASET_PATH: '/home/fahim/F2NetViT/Data/valid_list.txt'
TRAIN_BASE_PATH: '/home/fahim/F2NetViT/Dataset/BraTS2024-BraTS-GLI-TrainingData/training_data1_v2/'
VALID_BASE_PATH: '/home/fahim/F2NetViT/Dataset/BraTS2024-BraTS-GLI-ValidationData/'

target_dir: '/home/fahim/F2NetViT/Targets'
network_save_freq: 200  # based on the batch size, shows the number of epochs done; every half an hour is good
display_stats_freq: 1  # valid freq is equal to this
num_epochs: 10
TRAIN_SPLIT: 0.7
VALID_SPLIT: 0.1
TEST_SPLIT: 0.1
TRAIN_CUDA: True
